site_name: Glue
# TODO: fix
site_url: https://github.com/eankeen/glue
repo_url: https://github.com/eankeen/glue
repo_name: eankeen/glue
site_description: Glue is the manifestation of a generalized task runner with respect to language agnosticity
site_author: Edwin Kofler
copyright: © 2021
google_analytics: null
remote_branch: gh-pages
remote_name: origin
edit_uri: edit/main/docs
theme:
  name: material
  palette:
    scheme: slate # 'default' for light theme
    primary: deep orange
    accent: deep orange
  language: en
  # logo: assets/logo.png
  favicon: images/favicon.png
  features:
    # - navigation.instant
  icon:
    repo: fontawesome/brands/github
  extra:
    version:
      provider: mike
    social:
      - name: Edwin's DockerHub
        icon: fontawesome/brands/docker
        link: https://hub.docker.com/u/eankeen
      - name: Edwin's Medium
        icon: fontawesome/brands/medium
        link: https://medium.com/@eankeen
      - name: Edwin's Product Hunt
        icon: fontawesome/brands/product-hunt
        link: https://www.producthunt.com/@eankeen
      - name: Edwin's Twitter
        icon: fontawesome/brands/twitter
        link: https://twitter.com/eankeen
    copyright: Copyright &copy; 2021 Edwin Kofler
docs_dir: docs
site_dir: site
extra:
  version: 1.0
use_directory_urls: true
strict: true
dev_addr: 127.0.0.1:8000
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - admonition:
  - pymdownx.details
  # - pymdownx.superfences:
  #     # make exceptions to highlighting of code:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:mermaid2.fence_mermaid
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - def_list
  - meta
plugins:
  - search:
      separator: '[\s\-\.\_]+'
      min_search_length: 2
      lang: ['en']
      prebuild_index: false
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: false
      enable_creation_date: true
  - mike:
      version_selector: true
      canonical_version: null
  - mermaid2:
      arguments:
        theme: dark
  - macros
