image: archlinux
tasks:
    # TODO: not as root
    init:
        command: |
            pacman -Sy --noconfirm python poetry git
            # TODO:
            # poetry init --name 'packageName' --description 'Description' --author 'author' -l MIT
            poetry init -n
            poetry add mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mike mkdocs-mermaid2-plugin mkdocs-macros-plugin

    # init2:
    #     input_paths:
    #         - ./
    #     command: |
    #         poetry install

    mkdocs:
        dependencies:
            - init
            # - init2
        input_paths:
            - ./
        output_paths:
            - site
        command: |
            poetry run mkdocs build
